export const LOGIN_USER = "login_user";
export const REGISTER_USER = "register_user";
export const AUTH_USER = "auth_user";
export const LOGOUT_USER = "logout_user";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

// Places
export const LOAD_MAIN_PLACES_REQUEST = "LOAD_MAIN_PLACES_REQUEST";
export const LOAD_MAIN_PLACES_SUCCESS = "LOAD_MAIN_PLACES_SUCCESS";
export const LOAD_MAIN_PLACES_FAILURE = "LOAD_MAIN_PLACES_FAILURE";

export const LOAD_CATEGORIZED_PLACES_REQUEST =
  "LOAD_CATEGORIZED_PLACES_REQUEST";
export const LOAD_CATEGORIZED_PLACES_SUCCESS =
  "LOAD_CATEGORIZED_PLACES_SUCCESS";
export const LOAD_CATEGORIZED_PLACES_FAILURE =
  "LOAD_CATEGORIZED_PLACES_FAILURE";

export const ADD_PLACE_REQUEST = "ADD_PLACE_REQUEST";
export const ADD_PLACE_SUCCESS = "ADD_PLACE_SUCCESS";
export const ADD_PLACE_FAILURE = "ADD_PLACE_FAILURE";

export const LOAD_PLACE_DETAIL_REQUEST = "LOAD_PLACE_DETAIL_REQUEST";
export const LOAD_PLACE_DETAIL_SUCCESS = "LOAD_PLACE_DETAIL_SUCCESS";
export const LOAD_PLACE_DETAIL_FAILURE = "LOAD_PLACE_DETAIL_FAILURE";

export const SEARCH_PLACE_REQUEST = "SEARCH_PLACE_REQUEST";
export const SEARCH_PLACE_SUCCESS = "SEARCH_PLACE_SUCCESS";
export const SEARCH_PLACE_FAILURE = "SEARCH_PLACE_FAILURE";

export const LOAD_COMMENTS_REQUEST = "LOAD_COMMENTS_REQUEST";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_MORE_COMMENTS_SUCCESS = "LOAD_MORE_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_FAILURE = "LOAD_COMMENTS_FAILURE";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const LOAD_IS_LIKED_REQUEST = "LOAD_IS_LIKED_REQUEST";
export const LOAD_IS_LIKED_SUCCESS = "LOAD_IS_LIKED_SUCCESS";
export const LOAD_IS_LIKED_FAILURE = "LOAD_IS_LIKED_FAILURE";

export const TOGGLE_LIKE_REQUEST = "TOGGLE_LIKE_REQUEST";
export const TOGGLE_LIKE_SUCCESS = "TOGGLE_LIKE_SUCCESS";
export const TOGGLE_LIKE_FAILURE = "TOGGLE_LIKE_FAILURE";

export const TOGGLE_WISH_REQUEST = "TOGGLE_WISH_REQUEST";
export const TOGGLE_WISH_SUCCESS = "TOGGLE_WISH_SUCCESS";
export const TOGGLE_WISH_FAILURE = "TOGGLE_WISH_FAILURE";

export const LOAD_IMAGES_REQUEST = "LOAD_IMAGES_REQUEST";
export const LOAD_IMAGES_SUCCESS = "LOAD_IMAGES_SUCCESS";
export const LOAD_IMAGES_FAILURE = "LOAD_IMAGES_FAILURE";

export const UPLOAD_IMAGES_REQUEST = "UPLOAD_IMAGES_REQUEST";
export const UPLOAD_IMAGES_SUCCESS = "UPLOAD_IMAGES_SUCCESS";
export const UPLOAD_IMAGES_FAILURE = "UPLOAD_IMAGES_FAILURE";

export const EDIT_PLACE_REQUEST = "EDIT_PLACE_REQUEST";
export const EDIT_PLACE_SUCCESS = "EDIT_PLACE_SUCCESS";
export const EDIT_PLACE_FAILURE = "EDIT_PLACE_FAILURE";

export const REMOVE_IMAGE = "REMOVE_IMAGE";

export const SORT_BY_LIKES = "SORT_BY_LIKES";