export const LOGIN_USER = "login_user";
export const REGISTER_USER = "register_user";
export const AUTH_USER = "auth_user";
export const LOGOUT_USER = "logout_user";

// Places
export const LOAD_MAIN_PLACES_REQUEST = "LOAD_MAIN_PLACES_REQUEST";
export const LOAD_MAIN_PLACES_SUCCESS = "LOAD_MAIN_PLACES_SUCCESS";
export const LOAD_MAIN_PLACES_FAILURE = "LOAD_MAIN_PLACES_FAILURE";

export const LOAD_CATEGORIZED_PLACES_REQUEST =
  "LOAD_CATEGORIZED_PLACES_REQUEST";
export const LOAD_CATEGORIZED_PLACES_SUCCESS =
  "LOAD_CATEGORIZED_PLACES_SUCCESS";
export const LOAD_CATEGORIZED_PLACES_FAILURE =
  "LOAD_CATEGORIZED_PLACES_FAILURE";

export const ADD_PLACE_REQUEST = "ADD_PLACE_REQUEST";
export const ADD_PLACE_SUCCESS = "ADD_PLACE_SUCCESS";
export const ADD_PLACE_FAILURE = "ADD_PLACE_FAILURE";
